-- Sample seed data — 5 Hong Kong gyms for local dev / testing
-- Run after all migrations

insert into gyms (
  name,
  name_zh,
  slug,
  address,
  address_zh,
  district_code,
  country_code,
  postal_code,
  lat,
  lng,
  size_category,
  estimated_size_sqft,
  day_pass_price,
  is_active,
  is_verified,
  dumbbell_max_weight_kg,
  plate_min_weight_kg,
  plate_max_weight_kg,
  equipment_notes,
  data_source,
  equipment_last_verified_at
) values
(
  'IronBase HK (Wan Chai)',
  'IronBase HK（灣仔）',
  'ironbase-hk-wan-chai',
  '1 Harbour Rd, Wan Chai, Hong Kong',
  '香港灣仔港灣道1號',
  'HK-WC',
  'HK',
  null,
  22.2793,
  114.1720,
  'large',
  6000,
  200.00,
  true,
  true,
  60.0,
  1.25,
  25.0,
  'Strong free-weight setup with HYROX-friendly conditioning kit.',
  'admin',
  now()
),
(
  'Lift District Mong Kok',
  'Lift District 旺角',
  'lift-district-mong-kok',
  '68 Argyle St, Mong Kok, Hong Kong',
  '香港旺角亞皆老街68號',
  'HK-YTM',
  'HK',
  null,
  22.3193,
  114.1694,
  'medium',
  3500,
  180.00,
  true,
  true,
  50.0,
  2.5,
  25.0,
  'Compact gym with solid basics and useful accessory work.',
  'admin',
  now()
),
(
  'RackSpace Sha Tin',
  'RackSpace 沙田',
  'rackspace-sha-tin',
  '2-8 Yuen Wo Rd, Sha Tin, Hong Kong',
  '香港沙田源禾路2-8號',
  'HK-ST',
  'HK',
  null,
  22.3832,
  114.1876,
  'large',
  8000,
  150.00,
  true,
  false,
  70.0,
  1.25,
  25.0,
  'Large rack-heavy gym with plenty of conditioning space.',
  'user_submission',
  now() - interval '7 days'
),
(
  'Flex Studio Central',
  'Flex Studio 中環',
  'flex-studio-central',
  '18 Queen''s Rd Central, Central, Hong Kong',
  '香港中環皇后大道中18號',
  'HK-CW',
  'HK',
  null,
  22.2825,
  114.1558,
  'small',
  1200,
  280.00,
  true,
  true,
  40.0,
  2.5,
  20.0,
  'Small central studio with enough kit for general strength training.',
  'admin',
  now()
),
(
  'HYROX Hub Kwun Tong',
  'HYROX Hub 觀塘',
  'hyrox-hub-kwun-tong',
  '12 Hoi Yuen Rd, Kwun Tong, Hong Kong',
  '香港觀塘開源道12號',
  'HK-KT',
  'HK',
  null,
  22.3124,
  114.2261,
  'large',
  5500,
  160.00,
  true,
  true,
  50.0,
  2.5,
  25.0,
  'HYROX-focused gym with wall balls, sleds, rowers, and ski ergs.',
  'admin',
  now()
);

-- Canonical normalized equipment inventory. False and zero values are
-- retained as confirmed absence rather than being treated as unknown.
insert into gym_equipment_inventory (gym_id, equipment_code, is_present, quantity)
select
  gym.id,
  seed.equipment_code,
  seed.is_present,
  seed.quantity
from (values
  ('ironbase-hk-wan-chai', 'rack', ((6) > 0), 6),
  ('ironbase-hk-wan-chai', 'bench', ((8) > 0), 8),
  ('ironbase-hk-wan-chai', 'barbell', ((4) > 0), 4),
  ('ironbase-hk-wan-chai', 'platform', ((4) > 0), 4),
  ('ironbase-hk-wan-chai', 'roman_chair', true, null),
  ('ironbase-hk-wan-chai', 'dip_station', true, null),
  ('ironbase-hk-wan-chai', 'pull_up_bar', true, null),
  ('ironbase-hk-wan-chai', 'reverse_hyper', true, null),
  ('ironbase-hk-wan-chai', 'trap_bar', true, null),
  ('ironbase-hk-wan-chai', 'safety_squat_bar', true, null),
  ('ironbase-hk-wan-chai', 'farmer_handles', true, null),
  ('ironbase-hk-wan-chai', 'landmine_attachment', true, null),
  ('ironbase-hk-wan-chai', 'swiss_bar', true, null),
  ('ironbase-hk-wan-chai', 'cambered_bar', false, null),
  ('ironbase-hk-wan-chai', 'ez_bar', false, null),
  ('ironbase-hk-wan-chai', 'treadmill', ((8) > 0), 8),
  ('ironbase-hk-wan-chai', 'assault_bike', ((3) > 0), 3),
  ('ironbase-hk-wan-chai', 'exercise_bike', ((4) > 0), 4),
  ('ironbase-hk-wan-chai', 'climber', ((1) > 0), 1),
  ('ironbase-hk-wan-chai', 'assault_runner', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'ski_erg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'rower', ((4) > 0), 4),
  ('ironbase-hk-wan-chai', 'sled', ((1) > 0), 1),
  ('ironbase-hk-wan-chai', 'wall_ball', true, null),
  ('ironbase-hk-wan-chai', 'wall_ball_4kg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'wall_ball_6kg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'wall_ball_9kg', ((4) > 0), 4),
  ('ironbase-hk-wan-chai', 'wall_ball_plate_9ft', ((1) > 0), 1),
  ('ironbase-hk-wan-chai', 'wall_ball_plate_10ft', ((1) > 0), 1),
  ('ironbase-hk-wan-chai', 'workout_sandbag', true, null),
  ('ironbase-hk-wan-chai', 'sandbag_10kg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'sandbag_20kg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'sandbag_30kg', ((1) > 0), 1),
  ('ironbase-hk-wan-chai', 'kettlebell', true, null),
  ('ironbase-hk-wan-chai', 'kettlebell_16kg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'kettlebell_24kg', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'kettlebell_32kg', ((1) > 0), 1),
  ('ironbase-hk-wan-chai', 'cable_machine', ((4) > 0), 4),
  ('ironbase-hk-wan-chai', 'lat_pulldown_cable', true, null),
  ('ironbase-hk-wan-chai', 'seated_row_cable', true, null),
  ('ironbase-hk-wan-chai', 'smith_machine', ((2) > 0), 2),
  ('ironbase-hk-wan-chai', 'bicep_curl_machine', true, null),
  ('ironbase-hk-wan-chai', 'tricep_extension_machine', true, null),
  ('ironbase-hk-wan-chai', 'chest_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'incline_chest_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'iso_lateral_chest_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'pec_deck_machine', true, null),
  ('ironbase-hk-wan-chai', 'chest_fly_machine', true, null),
  ('ironbase-hk-wan-chai', 'lat_pulldown_machine', true, null),
  ('ironbase-hk-wan-chai', 'seated_row_machine', true, null),
  ('ironbase-hk-wan-chai', 'back_extension_machine', true, null),
  ('ironbase-hk-wan-chai', 'iso_lateral_row_machine', true, null),
  ('ironbase-hk-wan-chai', 't_bar_row_machine', true, null),
  ('ironbase-hk-wan-chai', 'lateral_raise_machine', true, null),
  ('ironbase-hk-wan-chai', 'reverse_fly_machine', true, null),
  ('ironbase-hk-wan-chai', 'shoulder_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'iso_lateral_shoulder_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'hip_abductor_machine', true, null),
  ('ironbase-hk-wan-chai', 'hip_adductor_machine', true, null),
  ('ironbase-hk-wan-chai', 'leg_extension_machine', true, null),
  ('ironbase-hk-wan-chai', 'leg_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'seated_leg_press_machine', true, null),
  ('ironbase-hk-wan-chai', 'lying_leg_curl_machine', true, null),
  ('ironbase-hk-wan-chai', 'seated_leg_curl_machine', true, null),
  ('ironbase-hk-wan-chai', 'seated_calf_raise_machine', true, null),
  ('ironbase-hk-wan-chai', 'squat_machine', true, null),
  ('ironbase-hk-wan-chai', 'standing_calf_raise_machine', true, null),
  ('ironbase-hk-wan-chai', 'battle_rope', true, null),
  ('ironbase-hk-wan-chai', 'foam_roller', true, null),
  ('ironbase-hk-wan-chai', 'medicine_ball', true, null),
  ('ironbase-hk-wan-chai', 'dip_belt', true, null),
  ('ironbase-hk-wan-chai', 'weight_vest', true, null),
  ('ironbase-hk-wan-chai', 'lifting_straps', true, null),
  ('ironbase-hk-wan-chai', 'plyo_box', true, null),
  ('ironbase-hk-wan-chai', 'balance_ball', true, null),
  ('lift-district-mong-kok', 'rack', ((4) > 0), 4),
  ('lift-district-mong-kok', 'bench', ((6) > 0), 6),
  ('lift-district-mong-kok', 'barbell', ((3) > 0), 3),
  ('lift-district-mong-kok', 'platform', ((2) > 0), 2),
  ('lift-district-mong-kok', 'roman_chair', false, null),
  ('lift-district-mong-kok', 'dip_station', true, null),
  ('lift-district-mong-kok', 'pull_up_bar', true, null),
  ('lift-district-mong-kok', 'reverse_hyper', false, null),
  ('lift-district-mong-kok', 'trap_bar', false, null),
  ('lift-district-mong-kok', 'safety_squat_bar', false, null),
  ('lift-district-mong-kok', 'farmer_handles', false, null),
  ('lift-district-mong-kok', 'landmine_attachment', true, null),
  ('lift-district-mong-kok', 'swiss_bar', false, null),
  ('lift-district-mong-kok', 'cambered_bar', false, null),
  ('lift-district-mong-kok', 'ez_bar', true, null),
  ('lift-district-mong-kok', 'treadmill', ((6) > 0), 6),
  ('lift-district-mong-kok', 'assault_bike', ((2) > 0), 2),
  ('lift-district-mong-kok', 'exercise_bike', ((3) > 0), 3),
  ('lift-district-mong-kok', 'climber', ((0) > 0), 0),
  ('lift-district-mong-kok', 'assault_runner', ((1) > 0), 1),
  ('lift-district-mong-kok', 'ski_erg', ((1) > 0), 1),
  ('lift-district-mong-kok', 'rower', ((2) > 0), 2),
  ('lift-district-mong-kok', 'sled', ((0) > 0), 0),
  ('lift-district-mong-kok', 'wall_ball', true, null),
  ('lift-district-mong-kok', 'wall_ball_4kg', ((1) > 0), 1),
  ('lift-district-mong-kok', 'wall_ball_6kg', ((1) > 0), 1),
  ('lift-district-mong-kok', 'wall_ball_9kg', ((2) > 0), 2),
  ('lift-district-mong-kok', 'wall_ball_plate_9ft', ((1) > 0), 1),
  ('lift-district-mong-kok', 'wall_ball_plate_10ft', ((0) > 0), 0),
  ('lift-district-mong-kok', 'workout_sandbag', false, null),
  ('lift-district-mong-kok', 'sandbag_10kg', ((0) > 0), 0),
  ('lift-district-mong-kok', 'sandbag_20kg', ((1) > 0), 1),
  ('lift-district-mong-kok', 'sandbag_30kg', ((0) > 0), 0),
  ('lift-district-mong-kok', 'kettlebell', true, null),
  ('lift-district-mong-kok', 'kettlebell_16kg', ((1) > 0), 1),
  ('lift-district-mong-kok', 'kettlebell_24kg', ((1) > 0), 1),
  ('lift-district-mong-kok', 'kettlebell_32kg', ((0) > 0), 0),
  ('lift-district-mong-kok', 'cable_machine', ((3) > 0), 3),
  ('lift-district-mong-kok', 'lat_pulldown_cable', true, null),
  ('lift-district-mong-kok', 'seated_row_cable', false, null),
  ('lift-district-mong-kok', 'smith_machine', ((0) > 0), 0),
  ('lift-district-mong-kok', 'bicep_curl_machine', true, null),
  ('lift-district-mong-kok', 'tricep_extension_machine', true, null),
  ('lift-district-mong-kok', 'chest_press_machine', true, null),
  ('lift-district-mong-kok', 'incline_chest_press_machine', false, null),
  ('lift-district-mong-kok', 'iso_lateral_chest_press_machine', false, null),
  ('lift-district-mong-kok', 'pec_deck_machine', true, null),
  ('lift-district-mong-kok', 'chest_fly_machine', false, null),
  ('lift-district-mong-kok', 'lat_pulldown_machine', true, null),
  ('lift-district-mong-kok', 'seated_row_machine', true, null),
  ('lift-district-mong-kok', 'back_extension_machine', false, null),
  ('lift-district-mong-kok', 'iso_lateral_row_machine', false, null),
  ('lift-district-mong-kok', 't_bar_row_machine', true, null),
  ('lift-district-mong-kok', 'lateral_raise_machine', true, null),
  ('lift-district-mong-kok', 'reverse_fly_machine', false, null),
  ('lift-district-mong-kok', 'shoulder_press_machine', true, null),
  ('lift-district-mong-kok', 'iso_lateral_shoulder_press_machine', false, null),
  ('lift-district-mong-kok', 'hip_abductor_machine', false, null),
  ('lift-district-mong-kok', 'hip_adductor_machine', false, null),
  ('lift-district-mong-kok', 'leg_extension_machine', true, null),
  ('lift-district-mong-kok', 'leg_press_machine', true, null),
  ('lift-district-mong-kok', 'seated_leg_press_machine', false, null),
  ('lift-district-mong-kok', 'lying_leg_curl_machine', true, null),
  ('lift-district-mong-kok', 'seated_leg_curl_machine', true, null),
  ('lift-district-mong-kok', 'seated_calf_raise_machine', false, null),
  ('lift-district-mong-kok', 'squat_machine', true, null),
  ('lift-district-mong-kok', 'standing_calf_raise_machine', false, null),
  ('lift-district-mong-kok', 'battle_rope', false, null),
  ('lift-district-mong-kok', 'foam_roller', true, null),
  ('lift-district-mong-kok', 'medicine_ball', true, null),
  ('lift-district-mong-kok', 'dip_belt', false, null),
  ('lift-district-mong-kok', 'weight_vest', false, null),
  ('lift-district-mong-kok', 'lifting_straps', false, null),
  ('lift-district-mong-kok', 'plyo_box', true, null),
  ('lift-district-mong-kok', 'balance_ball', true, null),
  ('rackspace-sha-tin', 'rack', ((8) > 0), 8),
  ('rackspace-sha-tin', 'bench', ((10) > 0), 10),
  ('rackspace-sha-tin', 'barbell', ((6) > 0), 6),
  ('rackspace-sha-tin', 'platform', ((6) > 0), 6),
  ('rackspace-sha-tin', 'roman_chair', true, null),
  ('rackspace-sha-tin', 'dip_station', true, null),
  ('rackspace-sha-tin', 'pull_up_bar', true, null),
  ('rackspace-sha-tin', 'reverse_hyper', true, null),
  ('rackspace-sha-tin', 'trap_bar', true, null),
  ('rackspace-sha-tin', 'safety_squat_bar', false, null),
  ('rackspace-sha-tin', 'farmer_handles', true, null),
  ('rackspace-sha-tin', 'landmine_attachment', true, null),
  ('rackspace-sha-tin', 'swiss_bar', true, null),
  ('rackspace-sha-tin', 'cambered_bar', true, null),
  ('rackspace-sha-tin', 'ez_bar', false, null),
  ('rackspace-sha-tin', 'treadmill', ((10) > 0), 10),
  ('rackspace-sha-tin', 'assault_bike', ((4) > 0), 4),
  ('rackspace-sha-tin', 'exercise_bike', ((6) > 0), 6),
  ('rackspace-sha-tin', 'climber', ((2) > 0), 2),
  ('rackspace-sha-tin', 'assault_runner', ((3) > 0), 3),
  ('rackspace-sha-tin', 'ski_erg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'rower', ((6) > 0), 6),
  ('rackspace-sha-tin', 'sled', ((2) > 0), 2),
  ('rackspace-sha-tin', 'wall_ball', true, null),
  ('rackspace-sha-tin', 'wall_ball_4kg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'wall_ball_6kg', ((4) > 0), 4),
  ('rackspace-sha-tin', 'wall_ball_9kg', ((6) > 0), 6),
  ('rackspace-sha-tin', 'wall_ball_plate_9ft', ((1) > 0), 1),
  ('rackspace-sha-tin', 'wall_ball_plate_10ft', ((1) > 0), 1),
  ('rackspace-sha-tin', 'workout_sandbag', true, null),
  ('rackspace-sha-tin', 'sandbag_10kg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'sandbag_20kg', ((4) > 0), 4),
  ('rackspace-sha-tin', 'sandbag_30kg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'kettlebell', true, null),
  ('rackspace-sha-tin', 'kettlebell_16kg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'kettlebell_24kg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'kettlebell_32kg', ((2) > 0), 2),
  ('rackspace-sha-tin', 'cable_machine', ((6) > 0), 6),
  ('rackspace-sha-tin', 'lat_pulldown_cable', true, null),
  ('rackspace-sha-tin', 'seated_row_cable', true, null),
  ('rackspace-sha-tin', 'smith_machine', ((2) > 0), 2),
  ('rackspace-sha-tin', 'bicep_curl_machine', true, null),
  ('rackspace-sha-tin', 'tricep_extension_machine', true, null),
  ('rackspace-sha-tin', 'chest_press_machine', true, null),
  ('rackspace-sha-tin', 'incline_chest_press_machine', true, null),
  ('rackspace-sha-tin', 'iso_lateral_chest_press_machine', true, null),
  ('rackspace-sha-tin', 'pec_deck_machine', true, null),
  ('rackspace-sha-tin', 'chest_fly_machine', true, null),
  ('rackspace-sha-tin', 'lat_pulldown_machine', true, null),
  ('rackspace-sha-tin', 'seated_row_machine', true, null),
  ('rackspace-sha-tin', 'back_extension_machine', true, null),
  ('rackspace-sha-tin', 'iso_lateral_row_machine', true, null),
  ('rackspace-sha-tin', 't_bar_row_machine', true, null),
  ('rackspace-sha-tin', 'lateral_raise_machine', true, null),
  ('rackspace-sha-tin', 'reverse_fly_machine', true, null),
  ('rackspace-sha-tin', 'shoulder_press_machine', true, null),
  ('rackspace-sha-tin', 'iso_lateral_shoulder_press_machine', true, null),
  ('rackspace-sha-tin', 'hip_abductor_machine', true, null),
  ('rackspace-sha-tin', 'hip_adductor_machine', true, null),
  ('rackspace-sha-tin', 'leg_extension_machine', true, null),
  ('rackspace-sha-tin', 'leg_press_machine', true, null),
  ('rackspace-sha-tin', 'seated_leg_press_machine', true, null),
  ('rackspace-sha-tin', 'lying_leg_curl_machine', true, null),
  ('rackspace-sha-tin', 'seated_leg_curl_machine', true, null),
  ('rackspace-sha-tin', 'seated_calf_raise_machine', true, null),
  ('rackspace-sha-tin', 'squat_machine', true, null),
  ('rackspace-sha-tin', 'standing_calf_raise_machine', true, null),
  ('rackspace-sha-tin', 'battle_rope', true, null),
  ('rackspace-sha-tin', 'foam_roller', true, null),
  ('rackspace-sha-tin', 'medicine_ball', true, null),
  ('rackspace-sha-tin', 'dip_belt', false, null),
  ('rackspace-sha-tin', 'weight_vest', true, null),
  ('rackspace-sha-tin', 'lifting_straps', true, null),
  ('rackspace-sha-tin', 'plyo_box', true, null),
  ('rackspace-sha-tin', 'balance_ball', true, null),
  ('flex-studio-central', 'rack', ((1) > 0), 1),
  ('flex-studio-central', 'bench', ((3) > 0), 3),
  ('flex-studio-central', 'barbell', ((1) > 0), 1),
  ('flex-studio-central', 'platform', ((1) > 0), 1),
  ('flex-studio-central', 'roman_chair', false, null),
  ('flex-studio-central', 'dip_station', false, null),
  ('flex-studio-central', 'pull_up_bar', true, null),
  ('flex-studio-central', 'reverse_hyper', false, null),
  ('flex-studio-central', 'trap_bar', false, null),
  ('flex-studio-central', 'safety_squat_bar', false, null),
  ('flex-studio-central', 'farmer_handles', false, null),
  ('flex-studio-central', 'landmine_attachment', false, null),
  ('flex-studio-central', 'swiss_bar', false, null),
  ('flex-studio-central', 'cambered_bar', false, null),
  ('flex-studio-central', 'ez_bar', false, null),
  ('flex-studio-central', 'treadmill', ((4) > 0), 4),
  ('flex-studio-central', 'assault_bike', ((1) > 0), 1),
  ('flex-studio-central', 'exercise_bike', ((2) > 0), 2),
  ('flex-studio-central', 'climber', ((0) > 0), 0),
  ('flex-studio-central', 'assault_runner', ((0) > 0), 0),
  ('flex-studio-central', 'ski_erg', ((0) > 0), 0),
  ('flex-studio-central', 'rower', ((2) > 0), 2),
  ('flex-studio-central', 'sled', ((0) > 0), 0),
  ('flex-studio-central', 'wall_ball', true, null),
  ('flex-studio-central', 'wall_ball_4kg', ((0) > 0), 0),
  ('flex-studio-central', 'wall_ball_6kg', ((1) > 0), 1),
  ('flex-studio-central', 'wall_ball_9kg', ((1) > 0), 1),
  ('flex-studio-central', 'wall_ball_plate_9ft', ((0) > 0), 0),
  ('flex-studio-central', 'wall_ball_plate_10ft', ((0) > 0), 0),
  ('flex-studio-central', 'workout_sandbag', false, null),
  ('flex-studio-central', 'sandbag_10kg', ((0) > 0), 0),
  ('flex-studio-central', 'sandbag_20kg', ((0) > 0), 0),
  ('flex-studio-central', 'sandbag_30kg', ((0) > 0), 0),
  ('flex-studio-central', 'kettlebell', false, null),
  ('flex-studio-central', 'kettlebell_16kg', ((0) > 0), 0),
  ('flex-studio-central', 'kettlebell_24kg', ((0) > 0), 0),
  ('flex-studio-central', 'kettlebell_32kg', ((0) > 0), 0),
  ('flex-studio-central', 'cable_machine', ((2) > 0), 2),
  ('flex-studio-central', 'lat_pulldown_cable', true, null),
  ('flex-studio-central', 'seated_row_cable', false, null),
  ('flex-studio-central', 'smith_machine', ((1) > 0), 1),
  ('flex-studio-central', 'bicep_curl_machine', false, null),
  ('flex-studio-central', 'tricep_extension_machine', false, null),
  ('flex-studio-central', 'chest_press_machine', true, null),
  ('flex-studio-central', 'incline_chest_press_machine', false, null),
  ('flex-studio-central', 'iso_lateral_chest_press_machine', false, null),
  ('flex-studio-central', 'pec_deck_machine', true, null),
  ('flex-studio-central', 'chest_fly_machine', true, null),
  ('flex-studio-central', 'lat_pulldown_machine', true, null),
  ('flex-studio-central', 'seated_row_machine', true, null),
  ('flex-studio-central', 'back_extension_machine', false, null),
  ('flex-studio-central', 'iso_lateral_row_machine', false, null),
  ('flex-studio-central', 't_bar_row_machine', false, null),
  ('flex-studio-central', 'lateral_raise_machine', true, null),
  ('flex-studio-central', 'reverse_fly_machine', true, null),
  ('flex-studio-central', 'shoulder_press_machine', true, null),
  ('flex-studio-central', 'iso_lateral_shoulder_press_machine', false, null),
  ('flex-studio-central', 'hip_abductor_machine', true, null),
  ('flex-studio-central', 'hip_adductor_machine', true, null),
  ('flex-studio-central', 'leg_extension_machine', true, null),
  ('flex-studio-central', 'leg_press_machine', true, null),
  ('flex-studio-central', 'seated_leg_press_machine', false, null),
  ('flex-studio-central', 'lying_leg_curl_machine', true, null),
  ('flex-studio-central', 'seated_leg_curl_machine', true, null),
  ('flex-studio-central', 'seated_calf_raise_machine', true, null),
  ('flex-studio-central', 'squat_machine', false, null),
  ('flex-studio-central', 'standing_calf_raise_machine', true, null),
  ('flex-studio-central', 'battle_rope', false, null),
  ('flex-studio-central', 'foam_roller', true, null),
  ('flex-studio-central', 'medicine_ball', true, null),
  ('flex-studio-central', 'dip_belt', false, null),
  ('flex-studio-central', 'weight_vest', false, null),
  ('flex-studio-central', 'lifting_straps', false, null),
  ('flex-studio-central', 'plyo_box', true, null),
  ('flex-studio-central', 'balance_ball', true, null),
  ('hyrox-hub-kwun-tong', 'rack', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'bench', ((6) > 0), 6),
  ('hyrox-hub-kwun-tong', 'barbell', ((3) > 0), 3),
  ('hyrox-hub-kwun-tong', 'platform', ((2) > 0), 2),
  ('hyrox-hub-kwun-tong', 'roman_chair', false, null),
  ('hyrox-hub-kwun-tong', 'dip_station', true, null),
  ('hyrox-hub-kwun-tong', 'pull_up_bar', true, null),
  ('hyrox-hub-kwun-tong', 'reverse_hyper', false, null),
  ('hyrox-hub-kwun-tong', 'trap_bar', false, null),
  ('hyrox-hub-kwun-tong', 'safety_squat_bar', false, null),
  ('hyrox-hub-kwun-tong', 'farmer_handles', false, null),
  ('hyrox-hub-kwun-tong', 'landmine_attachment', true, null),
  ('hyrox-hub-kwun-tong', 'swiss_bar', false, null),
  ('hyrox-hub-kwun-tong', 'cambered_bar', false, null),
  ('hyrox-hub-kwun-tong', 'ez_bar', false, null),
  ('hyrox-hub-kwun-tong', 'treadmill', ((8) > 0), 8),
  ('hyrox-hub-kwun-tong', 'assault_bike', ((6) > 0), 6),
  ('hyrox-hub-kwun-tong', 'exercise_bike', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'climber', ((1) > 0), 1),
  ('hyrox-hub-kwun-tong', 'assault_runner', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'ski_erg', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'rower', ((8) > 0), 8),
  ('hyrox-hub-kwun-tong', 'sled', ((2) > 0), 2),
  ('hyrox-hub-kwun-tong', 'wall_ball', true, null),
  ('hyrox-hub-kwun-tong', 'wall_ball_4kg', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'wall_ball_6kg', ((6) > 0), 6),
  ('hyrox-hub-kwun-tong', 'wall_ball_9kg', ((10) > 0), 10),
  ('hyrox-hub-kwun-tong', 'wall_ball_plate_9ft', ((1) > 0), 1),
  ('hyrox-hub-kwun-tong', 'wall_ball_plate_10ft', ((1) > 0), 1),
  ('hyrox-hub-kwun-tong', 'workout_sandbag', true, null),
  ('hyrox-hub-kwun-tong', 'sandbag_10kg', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'sandbag_20kg', ((6) > 0), 6),
  ('hyrox-hub-kwun-tong', 'sandbag_30kg', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'kettlebell', true, null),
  ('hyrox-hub-kwun-tong', 'kettlebell_16kg', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'kettlebell_24kg', ((4) > 0), 4),
  ('hyrox-hub-kwun-tong', 'kettlebell_32kg', ((2) > 0), 2),
  ('hyrox-hub-kwun-tong', 'cable_machine', ((3) > 0), 3),
  ('hyrox-hub-kwun-tong', 'lat_pulldown_cable', true, null),
  ('hyrox-hub-kwun-tong', 'seated_row_cable', true, null),
  ('hyrox-hub-kwun-tong', 'smith_machine', ((0) > 0), 0),
  ('hyrox-hub-kwun-tong', 'bicep_curl_machine', true, null),
  ('hyrox-hub-kwun-tong', 'tricep_extension_machine', true, null),
  ('hyrox-hub-kwun-tong', 'chest_press_machine', true, null),
  ('hyrox-hub-kwun-tong', 'incline_chest_press_machine', false, null),
  ('hyrox-hub-kwun-tong', 'iso_lateral_chest_press_machine', false, null),
  ('hyrox-hub-kwun-tong', 'pec_deck_machine', true, null),
  ('hyrox-hub-kwun-tong', 'chest_fly_machine', false, null),
  ('hyrox-hub-kwun-tong', 'lat_pulldown_machine', true, null),
  ('hyrox-hub-kwun-tong', 'seated_row_machine', true, null),
  ('hyrox-hub-kwun-tong', 'back_extension_machine', false, null),
  ('hyrox-hub-kwun-tong', 'iso_lateral_row_machine', true, null),
  ('hyrox-hub-kwun-tong', 't_bar_row_machine', false, null),
  ('hyrox-hub-kwun-tong', 'lateral_raise_machine', false, null),
  ('hyrox-hub-kwun-tong', 'reverse_fly_machine', false, null),
  ('hyrox-hub-kwun-tong', 'shoulder_press_machine', true, null),
  ('hyrox-hub-kwun-tong', 'iso_lateral_shoulder_press_machine', false, null),
  ('hyrox-hub-kwun-tong', 'hip_abductor_machine', false, null),
  ('hyrox-hub-kwun-tong', 'hip_adductor_machine', false, null),
  ('hyrox-hub-kwun-tong', 'leg_extension_machine', true, null),
  ('hyrox-hub-kwun-tong', 'leg_press_machine', true, null),
  ('hyrox-hub-kwun-tong', 'seated_leg_press_machine', false, null),
  ('hyrox-hub-kwun-tong', 'lying_leg_curl_machine', true, null),
  ('hyrox-hub-kwun-tong', 'seated_leg_curl_machine', true, null),
  ('hyrox-hub-kwun-tong', 'seated_calf_raise_machine', false, null),
  ('hyrox-hub-kwun-tong', 'squat_machine', true, null),
  ('hyrox-hub-kwun-tong', 'standing_calf_raise_machine', false, null),
  ('hyrox-hub-kwun-tong', 'battle_rope', true, null),
  ('hyrox-hub-kwun-tong', 'foam_roller', true, null),
  ('hyrox-hub-kwun-tong', 'medicine_ball', true, null),
  ('hyrox-hub-kwun-tong', 'dip_belt', false, null),
  ('hyrox-hub-kwun-tong', 'weight_vest', true, null),
  ('hyrox-hub-kwun-tong', 'lifting_straps', false, null),
  ('hyrox-hub-kwun-tong', 'plyo_box', true, null),
  ('hyrox-hub-kwun-tong', 'balance_ball', true, null)
) as seed(gym_slug, equipment_code, is_present, quantity)
join gyms gym on gym.slug = seed.gym_slug
on conflict (gym_id, equipment_code) do update
set is_present = excluded.is_present,
    quantity = excluded.quantity,
    updated_at = now();

-- Demo gym-brand mappings
insert into gym_brand_inventory (gym_id, brand_id, confidence)
select g.id, b.id, 'confirmed'
from gyms g
join equipment_brands b on b.slug in ('eleiko', 'rogue-fitness', 'hammer-strength', 'concept2')
where g.slug = 'ironbase-hk-wan-chai'
on conflict (gym_id, brand_id) do update
set confidence = excluded.confidence,
    updated_at = now();

insert into gym_brand_inventory (gym_id, brand_id, confidence)
select g.id, b.id, 'confirmed'
from gyms g
join equipment_brands b on b.slug in ('life-fitness', 'matrix-fitness', 'precor')
where g.slug = 'lift-district-mong-kok'
on conflict (gym_id, brand_id) do update
set confidence = excluded.confidence,
    updated_at = now();

insert into gym_brand_inventory (gym_id, brand_id, confidence)
select g.id, b.id, 'confirmed'
from gyms g
join equipment_brands b on b.slug in ('concept2', 'assault-fitness', 'rogue-fitness')
where g.slug = 'hyrox-hub-kwun-tong'
on conflict (gym_id, brand_id) do update
set confidence = excluded.confidence,
    updated_at = now();
