-- Let equipment count fields distinguish between:
--   NULL = not provided
--   0    = explicitly zero

alter table public.gyms
  alter column rack_count drop not null,
  alter column rack_count drop default,
  alter column bench_count drop not null,
  alter column bench_count drop default,
  alter column barbell_count drop not null,
  alter column barbell_count drop default,
  alter column assault_bike_count drop not null,
  alter column assault_bike_count drop default,
  alter column ski_erg_count drop not null,
  alter column ski_erg_count drop default,
  alter column rower_count drop not null,
  alter column rower_count drop default,
  alter column sled_count drop not null,
  alter column sled_count drop default,
  alter column treadmill_count drop not null,
  alter column treadmill_count drop default,
  alter column cable_machine_count drop not null,
  alter column cable_machine_count drop default,
  alter column lat_pulldown_count drop not null,
  alter column lat_pulldown_count drop default,
  alter column chest_press_count drop not null,
  alter column chest_press_count drop default,
  alter column leg_press_count drop not null,
  alter column leg_press_count drop default,
  alter column hack_squat_count drop not null,
  alter column hack_squat_count drop default,
  alter column exercise_bike_count drop not null,
  alter column exercise_bike_count drop default,
  alter column climber_count drop not null,
  alter column climber_count drop default,
  alter column assault_runner_count drop not null,
  alter column assault_runner_count drop default,
  alter column wall_ball_count drop not null,
  alter column wall_ball_count drop default,
  alter column wall_ball_4kg_count drop not null,
  alter column wall_ball_4kg_count drop default,
  alter column wall_ball_6kg_count drop not null,
  alter column wall_ball_6kg_count drop default,
  alter column wall_ball_9kg_count drop not null,
  alter column wall_ball_9kg_count drop default,
  alter column wall_ball_plate_9ft_count drop not null,
  alter column wall_ball_plate_9ft_count drop default,
  alter column wall_ball_plate_10ft_count drop not null,
  alter column wall_ball_plate_10ft_count drop default,
  alter column smith_machine_count drop not null,
  alter column smith_machine_count drop default,
  alter column sandbag_10kg_count drop not null,
  alter column sandbag_10kg_count drop default,
  alter column sandbag_20kg_count drop not null,
  alter column sandbag_20kg_count drop default,
  alter column sandbag_30kg_count drop not null,
  alter column sandbag_30kg_count drop default,
  alter column kettlebell_16kg_count drop not null,
  alter column kettlebell_16kg_count drop default,
  alter column kettlebell_24kg_count drop not null,
  alter column kettlebell_24kg_count drop default,
  alter column kettlebell_32kg_count drop not null,
  alter column kettlebell_32kg_count drop default;
