-- Let equipment boolean fields distinguish between:
--   NULL  = not provided
--   true  = explicitly available
--   false = explicitly not available

alter table public.gyms
  alter column has_smith_machine drop not null,
  alter column has_smith_machine drop default,
  alter column has_deadlift_platform drop not null,
  alter column has_deadlift_platform drop default,
  alter column has_pull_up_bar drop not null,
  alter column has_pull_up_bar drop default,
  alter column has_dip_station drop not null,
  alter column has_dip_station drop default,
  alter column has_trx drop not null,
  alter column has_trx drop default,
  alter column has_resistance_band drop not null,
  alter column has_resistance_band drop default,
  alter column has_battle_ropes drop not null,
  alter column has_battle_ropes drop default,
  alter column has_rings drop not null,
  alter column has_rings drop default,
  alter column has_glute_ham_developer drop not null,
  alter column has_glute_ham_developer drop default,
  alter column has_reverse_hyper drop not null,
  alter column has_reverse_hyper drop default,
  alter column has_farmers_handles drop not null,
  alter column has_farmers_handles drop default,
  alter column has_roman_chair drop not null,
  alter column has_roman_chair drop default,
  alter column has_trap_bar drop not null,
  alter column has_trap_bar drop default,
  alter column has_safety_squat_bar drop not null,
  alter column has_safety_squat_bar drop default,
  alter column has_farmer_handles drop not null,
  alter column has_farmer_handles drop default,
  alter column has_lat_pulldown_cable drop not null,
  alter column has_lat_pulldown_cable drop default,
  alter column has_seated_row_cable drop not null,
  alter column has_seated_row_cable drop default,
  alter column has_bicep_curl_machine drop not null,
  alter column has_bicep_curl_machine drop default,
  alter column has_tricep_extension_machine drop not null,
  alter column has_tricep_extension_machine drop default,
  alter column has_chest_press_machine drop not null,
  alter column has_chest_press_machine drop default,
  alter column has_incline_chest_press_machine drop not null,
  alter column has_incline_chest_press_machine drop default,
  alter column has_iso_lateral_chest_press_machine drop not null,
  alter column has_iso_lateral_chest_press_machine drop default,
  alter column has_pec_deck_machine drop not null,
  alter column has_pec_deck_machine drop default,
  alter column has_chest_fly_machine drop not null,
  alter column has_chest_fly_machine drop default,
  alter column has_lat_pulldown_machine drop not null,
  alter column has_lat_pulldown_machine drop default,
  alter column has_seated_row_machine drop not null,
  alter column has_seated_row_machine drop default,
  alter column has_back_extension_machine drop not null,
  alter column has_back_extension_machine drop default,
  alter column has_iso_lateral_row_machine drop not null,
  alter column has_iso_lateral_row_machine drop default,
  alter column has_t_bar_row_machine drop not null,
  alter column has_t_bar_row_machine drop default,
  alter column has_lateral_raise_machine drop not null,
  alter column has_lateral_raise_machine drop default,
  alter column has_reverse_fly_machine drop not null,
  alter column has_reverse_fly_machine drop default,
  alter column has_shoulder_press_machine drop not null,
  alter column has_shoulder_press_machine drop default,
  alter column has_iso_lateral_shoulder_press_machine drop not null,
  alter column has_iso_lateral_shoulder_press_machine drop default,
  alter column has_hip_abductor_machine drop not null,
  alter column has_hip_abductor_machine drop default,
  alter column has_hip_adductor_machine drop not null,
  alter column has_hip_adductor_machine drop default,
  alter column has_leg_extension_machine drop not null,
  alter column has_leg_extension_machine drop default,
  alter column has_leg_press_machine drop not null,
  alter column has_leg_press_machine drop default,
  alter column has_seated_leg_press_machine drop not null,
  alter column has_seated_leg_press_machine drop default,
  alter column has_lying_leg_curl_machine drop not null,
  alter column has_lying_leg_curl_machine drop default,
  alter column has_seated_leg_curl_machine drop not null,
  alter column has_seated_leg_curl_machine drop default,
  alter column has_seated_calf_raise_machine drop not null,
  alter column has_seated_calf_raise_machine drop default,
  alter column has_squat_machine drop not null,
  alter column has_squat_machine drop default,
  alter column has_standing_calf_raise_machine drop not null,
  alter column has_standing_calf_raise_machine drop default,
  alter column has_landmine_attachment drop not null,
  alter column has_landmine_attachment drop default,
  alter column has_swiss_bar drop not null,
  alter column has_swiss_bar drop default,
  alter column has_cambered_bar drop not null,
  alter column has_cambered_bar drop default,
  alter column has_ez_bar drop not null,
  alter column has_ez_bar drop default,
  alter column has_wall_ball drop not null,
  alter column has_wall_ball drop default,
  alter column has_sandbag drop not null,
  alter column has_sandbag drop default,
  alter column has_kettlebell drop not null,
  alter column has_kettlebell drop default,
  alter column has_battle_rope drop not null,
  alter column has_battle_rope drop default,
  alter column has_foam_roller drop not null,
  alter column has_foam_roller drop default,
  alter column has_medicine_ball drop not null,
  alter column has_medicine_ball drop default,
  alter column has_dip_belt drop not null,
  alter column has_dip_belt drop default,
  alter column has_weight_vest drop not null,
  alter column has_weight_vest drop default,
  alter column has_lifting_straps drop not null,
  alter column has_lifting_straps drop default,
  alter column has_plyo_box drop not null,
  alter column has_plyo_box drop default,
  alter column has_balance_ball drop not null,
  alter column has_balance_ball drop default;
